[project]
name = "mlx-conformer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.6"
dependencies = [
    "mlx>=0.24.2",
    "numpy>=2.2.4",
    "torchaudio>=2.6.0",
]
